---
title: "Julia"
date: 2023-10-28
date-modified: today
categories: [Installer]
---

## Installer Julia

Avec [juliaup](https://github.com/JuliaLang/juliaup#mac-and-linux).

## Installer IJulia

Voir la documentation de [quarto](https://quarto.org/docs/computations/julia.html#ijulia).

## Installer Revise.jl

En tapant `]` dans le Julia REPL, puis `add Revise`, tout simplement.

## Quitter le Pkg Mode

`Backspace` (juste au dessus de la touche `Enter`).

## Quitter Julia REPEL

Simplement `Ctrl + D` ou `exit()`.

## Utiliser Revise automatiquement avec Jupyter/IJulia

Voir la [documentation](https://timholy.github.io/Revise.jl/stable/config/#Using-Revise-automatically-within-Jupyter/IJulia) de Revise.jl.

## Installer Jupyter Cache

Avec `pip`, voir la [documentation](https://quarto.org/docs/computations/julia.html#installing-jupyter) de **quarto**.

## IDE options

Voir [Julia Data Science](https://juliadatascience.io/ide).

## VS Code

Voir le [billet dédié](https://tblk.github.io/excercices/visual-studio/).

# Parquet Files

- `Parquet` ne parvient pas à lire les fichiers parquet écrits avec les packages R `nanoparquet` et `arrow` de la manière la plus simple, c'est à dire avec `DataFrame(read_parquet(path))`.
- `ParquetFiles` renvoie une erreur... dès l'installation, et n'est en effet plus maintenu depuis 4 ans...
- `Parquet2`... Ça marche ! Et c'est bien celui qui est recommandé sur la page de `DataFrames` par exemple.
