project:
  type: website
  output-dir: docs

website:
  title: "Théo Boulakia"
  site-url: "https://tblk.github.io/"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - formation.qmd
      - enquetes.qmd
      - publications.qmd
      - cours.qmd
      - data-tips.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

lang: fr
