project:
  type: website
  output-dir: docs

website:
  title: "Théo Boulakia"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - these.qmd
      - attestation.qmd
      - these.qmd
      - lectures.qmd
      - posts.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



