project:
  type: website
  output-dir: docs

website:
  title: "Théo Boulakia"
  site-url: "https://tblk.github.io/"
  google-analytics: "G-PLYP4SVXT1"
  favicon: map.jpeg
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      # - formation.qmd
      # - enquetes.qmd
      - publications.qmd
      - interventions.qmd
      # - cours.qmd
      - data-tips.qmd

format:
  html:
    theme: darkly
    css: styles.css
    toc: true

lang: fr
