---
title: "Enquêtes"
linkcolor: "black"
---

## Solidarité Paysans

Comment des éleveurs ayant frôlé la faillite, et parfois considérés comme des parias par leurs pairs, parviennent-ils à persister dans le métier auxquels ils sont attachés, en le réinventant ? Cette première enquête, que j'ai mené en 2018 et 2019, reposait sur des entretiens biographiques avec des éleveurs de vaches laitières accompagnés par l'association [Solidarité Paysans](https://solidaritepaysans.org/). J'y ai pris conscience du rôle de la dette dans l'enracinement du système agricole intensif. J'ai aussi réalisé à quel point étaient précieux ces dispositifs, dont l'association Solidarité Paysans fait partie, par lesquels l'infortune devient dicible et réparable en commun.

## À quoi tient la conformité ?

L'enquête suivante m'a plongé dans des interactions bien différentes de l'accompagnement par les pairs. Je m'intéressais alors à la vie ordinaire d'un vaste dispositif de surveillance, d'incitation et de sanction. Une partie de mon terrain a eu lieu en 2020, mais il ne s'agissait pas (encore) d'enquêter sur le confinement. Ce qui me fascinait à l'époque, c'étaient les contrôles liés à la Politique Agricole Commune (PAC).

Chaque année, la plupart des agriculteurs français demandent les aides de la PAC. Entre avril et mai, ils déclarent par internet les caractéristiques de l'exploitation qui entrent dans le calcul des subventions : aides à l'hectares, aides animales, Indemnité compensatoire au handicap naturel (ICHN), aides agro-environnementales. L'ensemble de ces aides est soumis à la conditionnalité, c'est à dire que leur versement est subordonné au respect d'un corpus de normes. Lorsqu'ils sollicitent les subventions publiques, les agriculteurs s'exposent donc à des contrôles qui portent à la fois sur la véracité de leurs déclarations et le respect de leurs engagements. 

Les contrôles sont majoritairement réalisés par l'Agence des services et des paiements (ASP) et touchent chaque année 50 000 exploitations agricoles, soit 5 % des demandes d'aides. La moitié exigent la confrontation physique du contrôleur et de l'agriculteur, ils sont appelés "contrôles sur place". Les autres reposent uniquement sur des techniques de surveillance numériques, à partir de vues satellitaires. Ce sont les "contrôles à distance". 

Il y a de très nombreux types de contrôles. Par exemple, la première des sept Bonnes Conditions Agricoles et Environnementales (BCAE) porte sur le maintien d'une "bande tampon" le long des cours d'eau. Le contrôleur vérifie que la bande tampon mesure bien les 5 mètres réglementaires, qu'elle n'a été ni traitée ni fertilisée et qu'un couvert de type herbacé, arbustif ou arboré y est présent. 

L'idenfication des animaux est une autre obligation des éleveurs bénéficiaires d'aides publiques. Pour les bovins, le contrôleur vérifie que tous les animaux sont identifiés par deux boucles auriculaires agrées, que les naissances, achats, ventes et équarrissages sont notés dans le registre dédié, que chaque animal est muni d'un passeport lisible et cohérent avec ses caractéristiques et que l'exploitant a bien déclaré les mouvements de ses animaux -- entrée, sortie, mort ou naissance -- dans les sept jours. 

La plupart des "contrôles surface" sont réalisés par surveillance satellitaire. En cas de doute, un contrôleur se déplace, mesure à l'aide d'un GPS la taille des parcelles litigieuses et compare le résultat avec ce que l'agriculteur a déclaré sur internet. Cette opération est plus compliquée qu'il n'y paraît, car une série d'éléments "non admissibles" viennent en déduction de la surface primable. Ce sont par exemple les haies, les chemins, les broussailles et les zones de rocaille. Une variante de ce type de contrôle consiste à établir le "ratio de pâturabilité" des parcelles déclarées en pâturage permanent, en fonction du taux de couverture par les éléments non admissibles. Si le contrôleur estime qu'une parcelle est pâturable à 40 % seulement, l'éleveur touchera 40 % des aides auxquelles il aurait pu prétendre si elle avait été recouverte d'herbe de manière homogène. 

## L'Attestation

## Soin des bêtes et souci de soi
