---
title: Git et Github
description: Installer Git, puis connecter Git, Github et Rstudio (Linux et Mac)
date: today
categories: [Installer]
citation: 
  url: https://tblk.github.io/data-tips/git-et-github/ 
draft: false
---

## Vérifie si Git est installé

-   `which git`
-   S'il ne l'est pas : `brew install git`

## Présente toi à Git

-   `git config --global user.name 'Jane Doe'`
-   `git config --global user.email 'jane@example.com`
-   `git config --global --list`

## Cloner un repo

## Cacher le *Personnal access token*

Updates and shortens a post by Danielle Navarro.

For everyone :

-   If (and only if) no token yet : `usethis::create_github_token()`

-   Then cache it : `gitcreds::gitcreds_set()`

-   Check your git situation : `usethis::git_sitrep()`

Then, for Linux users only :

-   Download the [latest version of GCM](https://github.com/git-ecosystem/git-credential-manager/releases/tag/v2.1.2) (the .deb file)

-   Install it : `sudo dpkg -i <path-to-deb-file>`

-   `git-credential-manager configure`

::: callout-warning
[And not](https://github.com/git-ecosystem/git-credential-manager/blob/main/docs/rename.md) : `git-credential-manager-CORE configure`, as in Danielle Navarro's blog post.
:::

-   Check libsecret is installed (it should be) : `dpkg -s libsecret-1-0` The status should be Install ok Installed

-   `git config --global credential.credentialStore secretservice`

-   The first time you make a push, a window will open in your web browser, asking for password and a confirmation.
