---
title: "Site Web"
engine: knitr
description: "Guide de démarrage rapide et liens vers la documentation"
date: 2023-06-25
date-modified: today
categories: [Publier]
citation: 
  url: https://tblk.github.io/data-tips/site-web/ 
draft: false
execute: 
  eval: false
---

-   Crée un nouveau repo sur Github.

-   Clone le.

-   Ouvre le terminal dans le répertoire du projet (`Alt + Maj + M` dans Rstudio) et crée un projet de type `website`.

```{bash}
quarto create-project <site-name> --type website
```

Ou :

```{bash}
quarto create project website /
```

-   Dans le fichier `_quarto.yml`, choisir : `output-dir: docs`.

-   Ajouter à `.gitignore` les fichiers et dossiers qui ne doivent pas être publiés sur le site.

```{bash}
quarto render
```

-   Check all files in Git pane with this shortcut : `Ctrl+ A` then `Space`

-   Commit all pending changes : `Ctrl + Alt + M`

-   Push

-   Go to Github \> Settings \> Pages and "configure your GitHub repository to publish from the docs directory of your main branch" (quoting quarto documentation).

-   You're site will be deployed

## Preview image

Pour qu'un graphique en particulier serve de *preview image* :

```{{r}}
#| classes: preview-image
plot(mtcars)
```

## Code highlighting

Pour que du code `bash` ressorte correctement, choisir : `engine: knitr`. Voir [cette issue](https://github.com/quarto-dev/quarto-cli/discussions/5275).

::: callout-warning
Et ne surtout pas oublier l'option \`eval: false\` !
:::
