---
title: "Images"
engine: knitr
date: 2023-10-09
date-modified: today
description: "Utiliser ImageMagick pour convertir, compresser et transformer des images"
categories: [Manipuler]
citation: 
  url: https://tblk.github.io/data-tips/images/ 
draft: false
execute: 
  eval: false
---

## Convertir une image

```{bash}
convert image.jpg image.png
```

## Compresser une image

```{bash}
convert image.jpg[50%x50%] -quality 70 compressed_image.jpg
```

## Passer en nuances de gris

Ici, on utilise le package [magick](https://cran.r-project.org/web/packages/magick/vignettes/intro.html), qui rend accessible depuis `R` la librairie ImageMagick.

```{r}
#| eval: true
grenouille_arboricole = magick::image_read(
  "https://upload.wikimedia.org/wikipedia/commons/5/5a/Hyla_japonica_sep01.jpg"
  )

grenouille_arboricole
```

[Grenouille arboricole](https://commons.wikimedia.org/wiki/File:Hyla_japonica_sep01.jpg) photographiée le premier jour de septembre 2008. 池田正樹 (talk) masaki ikeda, CC BY-SA 3.0 <https://creativecommons.org/licenses/by-sa/3.0>, via Wikimedia Commons

```{r}
#| eval: true
grenouille_arboricole |>
  magick::image_quantize(colorspace = "gray")
```
