---
title: "Vidéos"
engine: knitr
date: 2023-09-28
date-modified: today
description: Installation et usage de yt-dlp
categories: [Récolter]
citation: 
  url: https://tblk.github.io/data-tips/videos/ 
draft: false
execute: 
  eval: false
  freeze: false
---

## Installation

```{bash}
pip install yt-dlp
```

Par ailleurs, s'assurer que ffmpeg est installé.

```{bash}
ffmpeg -version
```

Si ce n'est pas le cas :

```{bash}
sudo apt update
sudo apt install ffmpeg
```

## Mise à jour

L'intérêt d'installer avec pip est précisément de bénéficier des mises à jour plus rapidement qu'avec apt. Donc, si un téléchargement échoue :

```{bash}
pip install yt-dlp -U
```

## Télécharger

```{bash}
yt-dlp https://www.dailymotion.com/video/x7sv5fg
```

## Renommer

Il arrive en effet que le téléchargement échoue simplement parce que la nom de la vidéo est trop long. Dans ce cas, on peut renommer en même temps qu'on télécharge, ainsi :

```{bash}
yt-dlp https://youtu.be/M0yTTUt_zGA -o "new_name.mp4"
```

## Choisir

Pour choisir la meilleure qualité audio :

```{bash}
yt-dlp -F <url> # renvoie la liste des formats téléchargeables
yt-dlp -f <id> <url> # où l'id correspond à la première colonne
```

# Télécharger les sous-titres

```{bash}
yt-dlp --all-subs --skip-download <url>
```

## Fusionner audio et video avec ffmpeg

Il suffit d'ouvrir un terminal dans le dossier où sont rangés les fichiers audio et vidéo.

```{bash}
ffmpeg \
    -i video.mp4 -i audio.mp3 \
    -c:v copy \
    -map 0:v -map 1:a \
    -y output.mp4 
```

De très nombreuses options existent. Pour un petit aperçu, voir [ce billet de blog](https://www.linuxtricks.fr/wiki/yt-dlp-telecharger-des-videos-sur-internet-youtube-dl) de Linuxtricks, ou le [repo github](https://github.com/yt-dlp/yt-dlp).
