---
title: "Endettement"
date: 2023-11-28
execute: 
  echo: false
  eval: false
citation: 
  url: https://tblk.github.io/fiches/endettement/
---

```{r packages }
#| message: false
library(tidyverse)
library(DT)
library(dygraphs)
```

```{r data}
targets::tar_load(dettes, store = fs::path_home("these", "_targets"))
```

## Tableau

::: callout-note
**Taux d'endettement** : ensemble des dettes sur total de l'actif

**Annuités** : il s'agit uniquement des annuités des prêts à moyen et long terme.

Source : Réseau d'information comptable.

Tous les résultats sont des *moyennes*.
:::

```{r DT}
dettes |>
  select(milex, otefda, tdte3, anlmt, taudet_nr) |> 
  rename("Année" = milex,
         "Orientation" = otefda,
         "Ensemble des dettes" = tdte3,
        "Annuités" = anlmt,
         "Taux d'endettement" = taudet_nr) |> 
  DT::datatable(filter = list(position = 'top', clear = FALSE))
```

## Ensemble des dettes

```{r dygraph}
dettes |> 
  select(milex, otefda, tdte3) |> 
  filter(otefda %in% c("Bovin lait", "Grandes cultures", "Élevage hors sol")) |>
  pivot_wider(names_from = otefda, values_from = tdte3) |> 
  dygraph() |> 
  dyHighlight(highlightCircleSize = 5, 
              highlightSeriesBackgroundAlpha = 0.2,
              hideOnMouseOut = FALSE)
```
