---
title: "Zotero"
description: "Installation, Better Bibtex, Zutilo, Styles, OCR"
date: 2023-06-30
date-modified: today
categories: [Installer]
citation: 
  url: https://tblk.github.io/data-tips/zotero/ 
draft: false
engine: knitr
execute: 
  eval: false
---

## Préférences

Décocher :

-   ~~Faire une capture automatique des pages web~~

-   ~~Importer automatiquement les marqueurs~~

-   ~~Synchroniser automatiquement les fichiers joints dans ma bibliothèque~~

::: callout-tip
Si j'ai synchronisé la bibliothèque **avant** de décocher cette option : purger la bibliothèque (se fait en ligne).
:::

::: callout-note
Il est toujours possible de synchroniser les fichiers joints pour les **bibliothèques de groupe**. On peut ainsi annoter des pdf de manière collaborative.
:::

## Better Bibtex

-   Voir les instructions [ici](https://retorque.re/zotero-better-bibtex/installation/)

-   Les préférences de Better Bib Tex se trouvent dans l'onglet "Outils"

-   Choisir *auth.lower + year* comme clé de citation

## Zutilo

-   Voir les instructions [ici](https://github.com/wshanks/Zutilo)

-   Aller dans Outils \> Préférences de Zutilo et pour "copier les champs de la notice" et "coller dans les champs vides", choisir "menu contextuel de Zutilo".

## Styles

[Zotero styles repository](https://www.zotero.org/styles) & [Visual CSL Editor](https://editor.citationstyles.org/searchByExample/)

## Zotero OCR

Les instructions pour installer le plugin sont disponibles dans le [repo github](https://github.com/UB-Mannheim/zotero-ocr) correspondant.

Si Zotero ne trouve pas le chemin vers `pdftoppm` il suffit de le lui indiquer. On trouve ce chemin grâce à la commande `which` :

```{bash}
which pdftoppm
```

